import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header";
import Footer from "./_component/Footer";
import { ThemeProvider } from './_component/context/ThemeContext';
const inter = Ubuntu({ subsets: ["latin"], weight: '300', display: 'swap' });

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </ThemeProvider>

      </body>
    </html>
  );
}
